### ISSUE TITLE
Help Wanted: new version of this package slows down on real mechine

### ISSUE THREAD

**Issue by kfwu** [TheStarAlight/SemiclassicalSFI.jl#15]
Dear Developer:
Thank you for this amazing programme!

I first set it up in a Virtual Machine without using CUDA about a week ago. and it runs just fine.I tested the 'minimal example', after changing some variable and disabling GPU, the program runs at a speed of 1.6 s/it using 4 threats. latter I'd like to install it on a real machine with CUDA enabled. yet after changing most key words to fit the new package, this program runs at 22 s/it using 4 threats with CUDA enabled, and 1 min/it with CUDA disabled. The speed of newer version of pkg is also tested in my VM and the slow down is also observed (90s/it under -t 4 ).

the latter PC could passed the test(SemiclassicalSFI)  in 260min. Both are using pkg 1.4 version, though key words are different but the inputs are the same. I was wondering if this is anything to do with my environments, both are using julia 1.92 installed from snap, and python 3.10, in ubuntu 22.04. 

I have enclosed both input file in the end to see if there is anything wrong. please inform me if more information is needed.

In the end, I'd like to thank you again for sharing this well documented package, as an experimentalist this allow us to better understand our experiments.
Best Regard
Kefei

_______________________________________________________________

enclosed input files

_____________________________Inputs in real that runs slow___________________________________
```
using SemiclassicalSFI

filename = "SCSFI_HydLike_Ip_0.5662.h5"  # output file name


t = SemiclassicalSFI.Targets.HydrogenLikeAtom(Ip=0.5662, Z=1)


l = SemiclassicalSFI.Lasers.Cos2Laser(peak_int=3e14, wave_len=800, cyc_num=6, ellip=0.0)


SemiclassicalSFI.performSFI(

    init_cond_method = :ADK,
    laser = l,
    target = t,
    

    sample_t_interval = (-300,300),
    sample_t_num = 20000,

    final_p_max = (3,3,3),
    final_p_num = (800,800,1),

    traj_t_final = 400,
    save_3D_spec = false,

    ss_kd_max = 2.,
    ss_kd_num = 500,
    ss_kz_max = 2.,
    ss_kz_num = 150,

    traj_phase_method = :CTMC,

    traj_GPU = true,

    save_path = filename
    )
```

_____________________________Inputs in VM that runs faster___________________________________

```
using SemiclassicalSFI

filename = "SCSFI_HydLike_Ip_0.5662.h5"  # output file name


t = SemiclassicalSFI.Targets.HydrogenLikeAtom(Ip=0.5662, Z=1)


l = SemiclassicalSFI.Lasers.Cos2Laser(peak_int=3e14, wave_len=800, cyc_num=6, ellip=0.0)


SemiclassicalSFI.performSFI(

    ionRateMethod = :ADK,
    laser = l,
    target = t,
    

    sample_tSpan = (-300,300),
    sample_tSampleNum = 20000,


    finalMomentum_pMax = (3,3,3),
    finalMomentum_pNum = (800,800,1),

    simu_tFinal = 400,
    save_3D_momentumSpec = false,

    ss_kdMax = 2.,
    ss_kdNum = 500,
    ss_kzMax = 2.,
    ss_kzNum = 150,

    simu_phaseMethod = :CTMC,

    simu_GPU = false,

    save_fileName = filename
    )
```

**Comment by TheStarAlight** [comment]
Hi Kefei,

I'm glad to hear that our program has attracted attention from other researchers, even before our plan of publishing it :D

Note that you are using the dev branch of the program, which is unstable because the API may change at any time.
In fact this slow down is caused not by your switching to the real machine, but my modification to the simulation parameter😂...

GPU acceleration is currently realized by the [DiffEqGPU] package, which has limited support of customizing ensemble simulation parameters, thus it is still an experimental feature (we added the tag in the recent updates).
At first, the simulation configurations are different for CPU and GPU simply because the GPU's customization support is poor and I  just simply set the parameters at will since getting the code to run on GPU is already effort-consuming.
Recently I wanted to align the simulation configurations for CPU and GPU, however I found that the `rtol` parameter for adaptive methods didn't come into play for GPU, thus I changed to non-adaptive methods for both CPU and GPU and set the parameter `dt` (default `0.1`) to control the accuracy.
I guess this change in default accuracy may be the cause of your slow down this time.

**The solution is straightforward -- just adjust your `traj_dt` to make it larger**, it may affect the accuracy to some degree though. (maybe for linearly-polarized pulses, the trajectories close to the nucleus would be more sensitive to `dt`)
I haven't tested the most suitable `dt` for most cases, if you find that a larger `dt` like `0.2`, `0.25` is more suitable for a default `dt` value which reaches a balance between speed and accuracy, please inform me, and I'll be glad to adopt your value :D

Just tested your first script "Inputs in real that runs slow" with `traj_GPU=false` on my AMD R7950X with 4 threads, got the similar speed as you have 😂 60s/it...
Maybe we really need to consider a better default configuration, especially `dt`...
I'll be grateful if you can help in this, and I'm looking forward to further discussion~
Feel free to ask if you have any problem :D

Best Regards,
Mingyu Zhu

**Comment by TheStarAlight** [comment]
Cf. issue #16

**Comment by kfwu** [comment]
Hello Mingyu , Thanks for your reply!
I shall loose this parameter to see if the result if satisfactory.
cheers mate!

BTW is the unit of **traj_dt** in atomic unit? so 0.1 is about 2.4 as? I fear for **Ar** in a linear polarized light a much tighter one might be needed.  But for **H** I think 0.1 would suffice.

**Comment by TheStarAlight** [comment]
Hi @kfwu , yes you are right, 0.1 a.u. in time corresponds to 2.4 as, and I would like to note that our inputs are all in a.u. except the laser peak intensity (in W/cm2), wavelength (in nm), and the atoms' coordinates in `Molecule` (in Ang by default).

However I think the a.u. is somehow unfriendly to researchers who do experiments, who might be used to eV for ionization potential and energy, as&fs for laser temporal width, and Ang for atomic coordinates. Thus I decide to introduce the feature of specifying units (cf. #17). Ideas and suggestions are welcomed if you have any! :D

Thank you for your test and I'll be grateful if you can provide more information about this issue~ You may comment on #16 if you have some discoveries~~

Best Regards,
Mingyu Zhu
